# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '1f2c489a-8f9a-4f8b-b228-5059a236d64f'
  imageRepository: 'azurereactappneilacostaimage'
  containerRegistry: 'azurereactappneilacosta.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  #vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      #vmImage: $(vmImageName)
      name: Default #I am running the agent on local because Azure dont allow new accounts free to run jobs. 
                    #https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/windows-agent?view=azure-devops
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
