name: "DastArdly Secure Pipeline Test - Dast"
on: ["push","pull_request"]
jobs:
  dastchecktest:
    runs-on: ubuntu-latest
    steps:
      - name: Run Dastardly Action Step
        continue-on-error: true                        # This allows subsequent steps to run even if this step fails
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://neilacosta-web-react-app-tf.azurewebsites.net'
