name: Snyk Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm install # Adjust if using a different package manager or lockfile

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk to check for vulnerabilities
        run: snyk test --json > snyk_report.json || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: List files for debugging
        run: ls -la

      - name: Output Snyk report
        run: cat snyk_report.json

      - name: Upload Snyk results
        if: always()
        uses: actions/upload-artifact@v3
       
